app:
    resource: '@AppBundle/Controller/'
    type: annotation

products:
    type:   rest
    prefix: /api    
    resource: AppBundle\ApiController\ProductsController

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check